image: ruby:2.5.0

cashe:
  paths:
    - vendor/bundle
    - node_modules

variables:
  BUNDLE_PATH: vendor/bundle
  DISABLE_SPRING: 1

before_script:
  - mkdir -p ~/bin/ && export export PATH="~/bin/:$PATH"
  - curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o ~/bin/reviewdog && chmod +x ~/bin/reviewdog

reviewdog:
  script:
    - yarn
    - reviewdog -reporter=gitlab-mr-discussion
