AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 200

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - config/routes.rb

Bundler/OrderedGems:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/AbcSize:
  Max: 20
